[package]
name = "notate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
pandoc = "0.8.10"
regex = "1.9.5"
thiserror = "1.0.48"

[build-dependencies]
anyhow = "1.0.75"
which = "4.4.2"
